export const ALICE_MNEMONIC = "idle valley unveil champion dove echo bright advance mind image penalty sand slender random wage embrace bench only boring veteran use arch spy stomach";
export const BOB_MNEMONIC = "about soap pepper ball town maid settle fashion cupboard finger acoustic illness asthma prepare spawn cube cabin boss key flock save such phrase section";
export const EVE_MNEMONIC = "wing example cause action much bind wrong movie defense dilemma silent dutch noodle all blade expand drift security leg call isolate ensure omit wagon";

export const ALICE = "gvlt1u5dcaxv5nwwdjyj9pull6d02t9j57j5979nxxd";
export const BOB = "gvlt1l8s8afjml5n9qu2ph3c02qczdyl2urvfh054mh";
export const EVE = "gvlt17h6m2jacfyq0gjlwjy6s0uazms09pykgzwtend";
